export {default as Home} from "./Home"
export {default as Mp6} from "./Mp6"
export {default as Mp7} from "./Mp7"
export {default as EE} from "./EE"
export {default as Gas} from "./Gas"
export {default as Costs} from "./Costs"